version: "3.9"

services:
  bose-soundtouch-hybrid:
    image: node:18-alpine
    container_name: bose-soundtouch-hybrid
    working_dir: /app

    network_mode: "host"

    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - .env

    command: >
      sh -c "npm install && npm start"

    restart: unless-stopped
