services:
  bose-soundtouch-hybrid:
    image: node:18-alpine
    container_name: bose-soundtouch-hybrid
    working_dir: /app
    network_mode: "host"

    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro

    environment:
      APP_PORT: "8080"
      APP_HOST: "0.0.0.0"
      BASE_URL: "https://soundtouch.<deinedomain>"

    command: >
      sh -c "npm install && npm start"

    restart: unless-stopped
